apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role 
  namespace: webapps
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumesclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
    